name: DR2 Run Lambda Tests
on:
  pull_request:
  push:
    branches-ignore:
      - main
      - release-*
permissions:
  id-token: write
  contents: read
jobs:
  test:
    uses: nationalarchives/dr2-github-actions/.github/workflows/dr2_test.yml@main
    with:
      repo-name: dr2-notifications
      test-command: |
        python3 -m pip install botocore
        python3 -m pip install boto3
        python3 -m unittest
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
